# Generated by Django 4.2.4 on 2023-10-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazaMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_mascota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipomascota')),
            ],
        ),
    ]
