# Generated by Django 4.2.4 on 2023-10-07 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mascota_sexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='descripcion',
            new_name='detalles_adicionales',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='detalles',
            new_name='sobre_mi',
        ),
    ]
