# Generated by Django 4.2.4 on 2023-10-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mascota_perdida_alter_mascota_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('grant_type', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
