# Generated by Django 4.2.4 on 2023-10-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_servicioapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioapi',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
