# Generated by Django 4.2.4 on 2023-10-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_servicioapi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioapi',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
